<a href="https://colab.research.google.com/github/DWA-GIT/TESI-UNIFACISA/blob/master/RegressaoLinear2.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#Regressão Linear

importando as libs

In [0]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
import numpy as np

In [24]:
uri='https://raw.githubusercontent.com/DWA-GIT/TESI-UNIFACISA/master/movies_multilinear_reg.csv'
movies = pd.read_csv(uri)
movies.head(5)

movieId                              Titulo  ...  Investimento   Bilheteria
0        1                    Toy Story (1995)  ...     11.048216  5623234.602
1        2                      Jumanji (1995)  ...     14.927678  5714951.757
2        3             Grumpier Old Men (1995)  ...     27.114597  9524339.124
3        4            Waiting to Exhale (1995)  ...      4.994242  6331568.779
4        5  Father of the Bride Part II (1995)  ...     19.142246  6409617.277

[5 rows x 18 columns]

In [4]:
type(movies)

pandas.core.frame.DataFrame

In [0]:
movies.tail(10)

In [0]:
movies.shape

In [0]:
filmes_independente = movies[movies.columns[2:17]]

type(filmes_independente)

In [0]:
filmes_dependente = movies[movies.columns[17:]]

In [0]:
train, test, train_bilheteria, test_bilheteria =
train_test_split(filmes_independente, filmes_dependente)

In [14]:
train.head(3)

Documentary  Sci-Fi  Mystery  ...  Adventure     Duracao  Investimento
3127            0       0        0  ...          0  107.313318     26.673611
1328            0       0        0  ...          0  106.908752     17.747562
6468            0       0        0  ...          0  124.063076     12.050077

[3 rows x 15 columns]

In [17]:
train.shape[0]

6843

In [18]:
test.shape[0]

2282

In [20]:
percentual = test.shape[0] / movies.shape[0]
percentual

0.2500821917808219

In [21]:
modelo = LinearRegression()
modelo

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [22]:
modelo.fit(train, train_bilheteria)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

In [23]:
#Previsão do filme Toy Story
modelo.predict([[0,0,0,0,0,0,0,1,1,1,1,0,1,103.4683096,11.04821649]])

array([[5823768.34665006]])

In [25]:
acuracia = modelo.score(train,train_bilheteria )
acuracia

0.8249801443917903

Mudando o tamanho de treino

In [0]:
train, test, train_bilheteria, test_bilheteria = 
train_test_split(filmes_independente, filmes_dependente, test_size=0.3)

In [0]:
modelo_30 = LinearRegression()
modelo_30.fit(train, train_bilheteria)


In [35]:
acuracia_treino = modelo_30.score(train, train_bilheteria)
acuracia_treino

0.8269082909991625

In [37]:
zootopia = [0,0,0,0,0,0,0,0,1,1,1,0,1,145.5170642,3.451632127]
planeta_macaco = [0,1,0,0,0,0,0,0,0,0,0,0,0,150,5]
modelo_30.predict([zootopia])

array([[6959692.0057283]])

In [40]:
modelo_30.predict([planeta_macaco])

array([[7379168.07782218]])